### ISSUE TITLE
make-rpm.mk: simplify PKGNAME definition

### ISSUE THREAD

**Issue by oskrkal** [packagemgmt/make-plugins#17]
The first lines in `make-rpm.mk` contain this _PKGNAME_ variable definition:

```
ifndef PKGNAME
    PKGNAME:=$(shell test -f *.spec && basename *.spec .spec)
endif
```

This could probably be simplified to:

```
PKGNAME ?= $(shell test -f *.spec && basename *.spec .spec)
```

(Needs to be verified before implementing.)

**Comment by stardust85** [comment]
Makes sense :)
