### ISSUE TITLE
[documentation] How to build RPM for e.g. el6 only?

### ISSUE THREAD

**Issue by ghost** [packagemgmt/make-plugins#7]
..I mean some flag that tells which version to build?

**Comment by stardust85** [comment]
Yes. Please set a variable OS_VERSIONS=6 in your makefile before including my plug-in, or export env. variable OS_VERSIONS with value 6

**Comment by ghost** [comment]
Great! Thanks for lightning quick response. Closing issue..

**Comment by stardust85** [comment]
The docs should be updated. You can send a PR with the fixed Readme.md

**Comment by oskrkal** [comment]
README.md updated with description of configuration variables, including an example code of building RPMs for selected OS versions.
